In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
print(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.shape

(244, 7)

In [5]:
df.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [7]:
df.to_numpy()

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [8]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [13]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [16]:
df.to_parquet("tips.parquet")

In [17]:
pd.read_parquet("tips.parquet")

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
# rows where total_bill > 20
df[df["total_bill"] > 20]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

In [24]:
#Sort — the whole dataset by tip, descending.
df.sort_values(by="tip", ascending=False)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
..          ...    ...     ...    ...   ...     ...   ...
0         16.99   1.01  Female     No   Sun  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2

[244 rows x 7 columns]

In [28]:
#Groupby — average tip for each day.
df.groupby("day")["tip"].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [32]:
#find discrete values in all column
df.nunique()

total_bill    229
tip           123
sex             2
smoker          2
day             4
time            2
size            6
dtype: int64

In [ ]:
#creating a small second DataFrame mapping day abbreviations to full names (e.g. {"Thur": "Thursday", "Fri": "Friday", ...} then merge it onto df using day as the key.
day_df = pd.DataFrame({"day": ["Thur", "Fri", "Sat", "Sun"], "full_day": ["Thursday", "Friday", "Saturday", "Sunday"]})
df.merge(day_df, on="day")

     total_bill   tip     sex smoker   day    time  size  full_day
0         16.99  1.01  Female     No   Sun  Dinner     2    Sunday
1         10.34  1.66    Male     No   Sun  Dinner     3    Sunday
2         21.01  3.50    Male     No   Sun  Dinner     3    Sunday
3         23.68  3.31    Male     No   Sun  Dinner     2    Sunday
4         24.59  3.61  Female     No   Sun  Dinner     4    Sunday
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  Saturday
240       27.18  2.00  Female    Yes   Sat  Dinner     2  Saturday
241       22.67  2.00    Male    Yes   Sat  Dinner     2  Saturday
242       17.82  1.75    Male     No   Sat  Dinner     2  Saturday
243       18.78  3.00  Female     No  Thur  Dinner     2  Thursday

[244 rows x 8 columns]

In [37]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [46]:
#a pivot table of average total_bill by day (rows) and time (columns), using pd.pivot_table
df.pivot_table(values="total_bill", index="day", columns="time")

time     Dinner      Lunch
day
Fri   19.663333  12.845714
Sat   20.441379        NaN
Sun   21.410000        NaN
Thur  18.780000  17.664754

In [49]:
df.pivot_table(values="total_bill", index="day", columns="time", aggfunc=["sum","min","max","count"])

          sum             min          max         count
time   Dinner    Lunch Dinner Lunch Dinner  Lunch Dinner Lunch
day
Fri    235.96    89.92   5.75  8.58  40.17  16.27   12.0   7.0
Sat   1778.40      NaN   3.07   NaN  50.81    NaN   87.0   NaN
Sun   1627.16      NaN   7.25   NaN  48.17    NaN   76.0   NaN
Thur    18.78  1077.55  18.78  7.51  18.78  43.11    1.0  61.0